[env:seeeduino_xiao_esp32c3]
platform = espressif32
board = seeeduino_xiao_esp32c3
framework = arduino
upload_speed = 921600
monitor_speed = 115200

; 共有ファイルのincludeパス設定
build_flags = -I ./include

; ESP32C3用の必須ライブラリ
lib_deps = 
    SoftwareSerial
    TFT_eSPI
